from __future__ import annotations

from dataclasses import dataclass

from .ast_nodes import (
    Assignment,
    BinaryOperation,
    Identifier,
    Number,
    PrintStatement,
    Program,
    WhenStatement,
    VarDeclaration,
    LoopStatement,
    String,
    Boolean,
)
from .ir import IRProgram


@dataclass
class CodeGenerator:
    """Generate pseudo assembly and equivalent Python code from IR."""

    def generate_assembly(self, ir_program: IRProgram) -> str:
        lines: list[str] = []
        for instruction in ir_program.instructions:
            if instruction.op == "LABEL":
                lines.append(f"{instruction.label}:")
            elif instruction.op == "GOTO":
                lines.append(f"JMP {instruction.label}")
            elif instruction.op == "IF_GOTO":
                lines.append(f"JNZ {instruction.arg1}, {instruction.label}")
            elif instruction.op == "PRINT":
                lines.append(f"PRINT {instruction.arg1}")
            elif instruction.op == "ASSIGN":
                lines.append(f"LOAD {instruction.result}, {instruction.arg1}")
                lines.append(f"STORE {instruction.result}")
            elif instruction.op == "BINARY":
                operator, right_operand = instruction.arg2.split(" ", 1)
                mnemonic = self.operator_to_mnemonic(operator)
                lines.append(f"LOAD {instruction.result}, {instruction.arg1}")
                lines.append(f"{mnemonic} {instruction.result}, {right_operand}")
                lines.append(f"STORE {instruction.result}")
        return "\n".join(lines)

    def generate_python(self, program: Program) -> str:
        lines: list[str] = ["# Equivalent Python code generated by FlowLang compiler"]
        for statement in program.statements:
            lines.extend(self._emit_python_statement(statement, 0))
        return "\n".join(lines)

    def _emit_python_statement(self, node, indent_level: int) -> list[str]:
        indent = "    " * indent_level
        if isinstance(node, VarDeclaration):
            init = node.init if node.init is not None else Number(0)
            return [f"{indent}{node.name} = {self._emit_python_expression(init)}"]
        if isinstance(node, Assignment):
            return [f"{indent}{node.name} = {self._emit_python_expression(node.expression)}"]
        if isinstance(node, PrintStatement):
            return [f"{indent}print({self._emit_python_expression(node.expression)})"]
        if isinstance(node, WhenStatement):
            lines = [f"{indent}if {self._emit_python_expression(node.condition)}:"]
            for statement in node.body:
                lines.extend(self._emit_python_statement(statement, indent_level + 1))
            return lines
        if isinstance(node, LoopStatement):
            lines = [f"{indent}while {self._emit_python_expression(node.condition)}:"]
            for statement in node.body:
                lines.extend(self._emit_python_statement(statement, indent_level + 1))
            return lines
        raise TypeError(f"Unsupported statement type: {type(node).__name__}")

    def _emit_python_expression(self, node) -> str:
        if isinstance(node, Number):
            return str(int(node.value)) if isinstance(node.value, float) and node.value.is_integer() else str(node.value)
        if isinstance(node, String):
            return repr(node.value)
        if isinstance(node, Boolean):
            return "True" if node.value else "False"
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, BinaryOperation):
            left = self._emit_python_expression(node.left)
            right = self._emit_python_expression(node.right)
            return f"({left} {node.operator} {right})"
        raise TypeError(f"Unsupported expression type: {type(node).__name__}")

    def operator_to_mnemonic(self, operator: str) -> str:
        return {
            "+": "ADD",
            "-": "SUB",
            "*": "MUL",
            "/": "DIV",
            ">": "CMP_GT",
            "<": "CMP_LT",
            ">=": "CMP_GE",
            "<=": "CMP_LE",
            "==": "CMP_EQ",
            "!=": "CMP_NE",
            "%": "MOD",
            "**": "POW",
            "&&": "AND",
            "||": "OR",
        }[operator]
